server:
  servlet:
    context-path: /amt    #context path for the rest services
  port: 8090

# Custom property mqtt configuration
mqtt-properties:
  host: tcp://localhost:1883
  clientId: adarsh-model-trains-transformer-
  username: adarsh
  password: password
  topicSub: /trains/track/#
  lightTopic: /trains/track/light/
  turnoutTopic: /trains/track/turnout/
  signalTopic: /trains/track/signalhead/
  topicPub: /amt/node/
  cleanSession: true
  connectionTimeout: 300
  keepAliveInterval: 60
  automaticReconnect: true


# Custom property for nodes configuration
node:
  configurations:
    lightStartingAddress: 10000
    turnoutStartingAddress: 20000
    signalStartingAddress: 30000
    nodes:
      -
        nodeId: 1
        lightStartAddress: 10000
        lightCount: 10
        turnoutStartAddress: 20000
        turnoutCount: 16
        signalStartAddress: 30000
        signalCount: 36
        turnoutBoardCount: 3
        lightBoardCount: 3
      -
        nodeId: 2
        lightStartAddress: 10100
        lightCount: 27
        turnoutStartAddress: 20100
        turnoutCount: 48
        signalStartAddress: 30100
        signalCount: 81
        turnoutBoardCount: 6
        lightBoardCount: 7
      -
        nodeId: 3
        lightStartAddress: 10200
        lightCount: 7
        turnoutStartAddress: 20200
        turnoutCount: 27
        signalStartAddress: 30200
        signalCount: 87
        turnoutBoardCount: 4
        lightBoardCount: 6
      -
        nodeId: 4
        lightStartAddress: 10300
        lightCount: 23
        turnoutStartAddress: 20300
        turnoutCount: 10
        signalStartAddress: 30300
        signalCount: 24
        turnoutBoardCount: 2
        lightBoardCount: 3
      -
        nodeId: 5
        lightStartAddress: 10400
        lightCount: 45
        turnoutStartAddress: 20400
        turnoutCount:
        signalStartAddress: 30400
        signalCount: 80
        turnoutBoardCount: 10
        lightBoardCount: 8
      -
        nodeId: 6
        lightStartAddress: 10500
        lightCount: 10
        turnoutStartAddress: 20500
        turnoutCount: 15
        signalStartAddress: 30500
        signalCount: 45
        turnoutBoardCount: 2
        lightBoardCount: 4
      -
        nodeId: 7
        lightStartAddress: 10600
        lightCount: 12
        turnoutStartAddress: 20600
        turnoutCount: 48
        signalStartAddress: 30600
        signalCount: 80
        turnoutBoardCount: 6
        lightBoardCount: 6
      -
        nodeId: 8
        lightStartAddress: 10700
        lightCount: 7
        turnoutStartAddress: 20700
        turnoutCount: 21
        signalStartAddress: 30700
        signalCount: 87
        turnoutBoardCount: 3
        lightBoardCount: 6
      -
        nodeId: 9
        lightStartAddress: 10800
        lightCount: 23
        turnoutStartAddress: 20800
        turnoutCount: 10
        signalStartAddress: 30800
        signalCount: 24
        turnoutBoardCount: 3
        lightBoardCount: 3
      -
        nodeId: 10
        lightStartAddress: 10900
        lightCount: 45
        turnoutStartAddress: 20900
        turnoutCount: 23
        signalStartAddress: 30900
        signalCount: 80
        turnoutBoardCount: 3
        lightBoardCount: 8