server:
  servlet:
    context-path: /amt
  port: 8090

# Custom property mqtt configuration
mqtt-properties:
  host: tcp://localhost:1883
  clientId: adarsh-model-trains-transformer-
  username: adarsh
  password: password
  topicSub: /trains/track/#
  topicPub: /amt/node/
  cleanSession: true
  connectionTimeout: 300
  keepAliveInterval: 60
  # If this property is set to true, the connection will be automatically reconnected when disconnected
  automaticReconnect: true


node:
  configurations:
    nodes:
      -
        nodeNo: 1
        lightStartAddress: 1000
        lightCount: 10
        turnoutStartAddress: 2000
        turnoutCount: 15
        signalStartAddress: 3000
        signalCount: 37
      -
        nodeNo: 2
        lightStartAddress: 1100
        lightCount: 27
        turnoutStartAddress: 2100
        turnoutCount: 48
        signalStartAddress: 3100
        signalCount: 80
      -
        nodeNo: 3
        lightStartAddress: 1200
        lightCount: 7
        turnoutStartAddress: 2200
        turnoutCount: 27
        signalStartAddress: 3200
        signalCount: 87
      -
        nodeNo: 4
        lightStartAddress: 1300
        lightCount: 23
        turnoutStartAddress: 2300
        turnoutCount: 10
        signalStartAddress: 3300
        signalCount: 24
      -
        nodeNo: 5
        lightStartAddress: 1400
        lightCount: 45
        turnoutStartAddress: 2400
        turnoutCount: 78
        signalStartAddress: 3400
        signalCount: 80
      -
        nodeNo: 6
        lightStartAddress: 1500
        lightCount: 10
        turnoutStartAddress: 2500
        turnoutCount: 15
        signalStartAddress: 3500
        signalCount: 37
      -
        nodeNo: 7
        lightStartAddress: 1600
        lightCount: 27
        turnoutStartAddress: 2600
        turnoutCount: 48
        signalStartAddress: 3600
        signalCount: 80
      -
        nodeNo: 8
        lightStartAddress: 1700
        lightCount: 7
        turnoutStartAddress: 2700
        turnoutCount: 27
        signalStartAddress: 3700
        signalCount: 87
      -
        nodeNo: 9
        lightStartAddress: 1800
        lightCount: 23
        turnoutStartAddress: 2800
        turnoutCount: 10
        signalStartAddress: 3800
        signalCount: 24
      -
        nodeNo: 10
        lightStartAddress: 1900
        lightCount: 45
        turnoutStartAddress: 2900
        turnoutCount: 78
        signalStartAddress: 3900
        signalCount: 80